analytics: {}
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.438322
  lightness: 0.254112
  rhythmicContrast: 0.514803
  saturation: 0.137336
cta: {}
layout_spectrum: 0.530822
name: LAZARUS XI
opengraph: {}
purpose: []
typography_spectrum: 0.736301
